import {
  reactive
} from 'vue'
export const AllData = reactive({
 Data16: `6E7AA8A500A1CFAACEB2CBAEBFE23200C3F7BDD8CEDBD5A2C7B000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF003836313338303038313835303000FF003131322E3039342E3036372E313138003131322E3039342E3036372E313138003030302E3030302E3030302E303030003030302E3030302E3030302E303030003034372E3039372E3033352E30333300234E234E00000000BB040000000000050B00000000000000000000000000000000000000000000000000000011000000000000000000000000000000000000000000000000000000000000000A000000000000000000000000000000000000001027000010270000000000000000000000000500FFFFFFFFE803E803E803E803E803E80300000500A00F0000A00F0000204E0000204E000000000000E1FFFFFF131000000000000000000000F4010000BC0200002C0100000000000000000000000000000000000000000000000000000000000000000000E803000000000000000000000000000000000000000000000000000000000000E707020003000A001E000A00FFFFFFFFFFFF050005007800E803E803E803E803E80300000000000000000000686803003412341234123412000000001027102700000000E803E803000000006400640064006400640064000000000000000000000000000000000000000011000000000000000000000000000000000000000000009101000000000000000001021E1F202122232425010A1817160915EB0B0E0D071415161718191A1B08090A0A0B0C0D0E0F101101021F060A0102F33FFFFF20212211111111110505050100000100000001000304050101FFFFFFFFFFFFFFFFFF00010210101000730000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF001E1E1E1E1E0000FFFFFFFF78FFFF00FFFFFFFF0000FF0000000102010104FF00636D6E657400FFFFFFFFFFFFFFFFFFFF00636D6E657400FFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000200FFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000003A8D967133A00FFFFFFFFFFFFFFFF000000000073657665723100FFFFFFFFFFFFFFFF0073657665723300FFFFFFFFFFFFFFFF0073657665723300FFFFFFFFFFFFFFFF0073657665723200FFFFFFFFFFFFFFFF000202010101000000030303000005FFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000FF000000000500000000000000000001010100000000000000000000000000005823230A0A0505010F05013C0F0105050000000000000000000000000000000000D1EA`,
  FloodSeasonModeList:[
    { text: "汛期", value: "1" },
    { text: "非汛期", value: "0" },
  ],
  AdditionalMmodeList:[
    { text: "手动模式", value: "0" },
    { text: "阙值加报模式", value: "1" },
  ],
  YzcTeleTypeList:[
    { text: "降水", value: 0 },
    { text: "河道", value: 1 },
    { text: "水库（湖泊）", value: 2 },
    { text: "闸坝", value: 3 },
    { text: "泵站", value: 4 },
    { text: "潮汐", value: 5 },
    { text: "墒情", value: 6 },
    { text: "地下水", value: 7 },
    { text: "水质", value: 8 },
    { text: "取水口", value: 9 },
    { text: "排水口", value: 10 },
    { text: "窘井", value: 11 },
    { text: "官网", value: 12 },
    { text: "内涝", value: 13 },
    { text: "河道（三防", value: 14 },
    { text: "险情（三防）", value: 15 },
  ],
  SiteTypeList:[
    { text: "WGX20-A-1激光水位计", value: "0" },
    { text: "XF-WQX80-气泡位计", value: "1" },
    { text: "XF-WYZ-1压力水位计", value: "2" },
    { text: "420mA压力水位计", value: "3" },
    { text: "420mA雷达水位计", value: "4" },
    { text: "YLN-YQS气泡位计", value: "5" },
    { text: "WT-WTZ-1雷达水位计", value: "6" },
    { text: "DYYX-WW超声波水位计", value: "7" },
    { text: "WFX_40浮子水位计", value: "8" },
    { text: "MFM4700压力水位计", value: "9" },
    { text: "WDC电子水尺", value: "10" },
    { text: "KYB19压力水位计", value: "11" },
    { text: "RD-300s雷达水位计", value: "12" },
    { text: "NF-WGX-5小雷达水位计", value: "13" },
    { text: "NF-WGX-6大雷达水位计", value: "14" },
    { text: "VWP_0.35硅压水位计", value: "15" },
    { text: "TC-FMCR15F雷达水位计", value: "16" },
  ],
  DataKey: 0,
  // Data16: `0001`,
  // Data16: `6E7AA8A5303132333435363738396162636465666700D5A2C7B000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00`,
  //字节数组数据
  DataZijie: [],
  Data_form: [
    {
      name: "ID",
      nameZn: "ID",
      type: "u",
      num: 32,
      value: "",
      analysis: true,
    },
    
    {
      name: "TelName",
      nameZn: "遥测站名字",
      type: "char",
      num: 64,
      value: "",
     analysis: true,
    },
    {
      name: "ThisPhone",
      nameZn: "本机SIM卡电话号码",
      type: "char",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "ThisSMSNumber",
      nameZn: "本机SIM卡短信中心号码",
      type: "char",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "ServerIP",
      nameZn: "服务器地址",
      type: "char",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "ServerPort",
      nameZn: "服务器端口",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },

    {
      name: "TelNumber",
      nameZn: "遥测站编码",
      type: "u",
      num: 40,
      value: "",
     analysis: true,
    },
    {
      name: "AlarmTime",
      nameZn: "加报报间隔",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TeleType",
      nameZn: "遥测站类型",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "CommMessageProtocolIndex",
      nameZn: "中心站",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "StandbyServerPort",
      nameZn: "备用服务器端口",
      type: "u",
      num: 192,
      value: "",
     analysis: false,
    },
    {
      name: "ServerConfig",
      nameZn: "服务器相关配置",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "InsideDTU_Type",
      nameZn: "内部DTU类型定义",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "HourCycle",
      nameZn: "小时报周期",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "HourCycle",
      nameZn: "小时报周期",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevelHight",
      nameZn: "水位计探头安装高度",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevelHAlarm",
      nameZn: "低报警水位",
      type: "u",
      num: 64,
      value: "",
     analysis: true,
    },
    {
      name: "WaterLevelLAlarm",
      nameZn: "水位计低报警水位",
      type: "u",
      num: 64,
      value: "",
     analysis: true,
    },
    {
      name: "WaterLevelAlarmH",
      nameZn: "水位计报警水位以上报警水位",
      type: "u",
      num: 32,
      value: "",
     analysis: true,
    },
    {
      name: "WaterLevelAlarmL",
      nameZn: "水位计报警水位以下报警水位",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "WaterBaseLevel",
      nameZn: "水位基准面",
      type: "s",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "WaterCorrectionLevel",
      nameZn: "水位修正值",
      type: "s",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "WaterCorrParame",
      nameZn: "水位计线性修正值",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "WaterCorrParame",
      nameZn: "水位计线性修正值",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "ManualSetRand",
      nameZn: "人工置数浮动值",
      type: "u",
      num: 80,
      value: "",
     analysis: false,
    },
    {
      name: "TimeCycle",
      nameZn: "定时报发送周期",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "res32",
      nameZn: "",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "LZX1_K",
      nameZn: "水龟校准系数",
      type: "u",
      num: 96,
      value: "",
     analysis: false,
    },
    {
      name: "LZX1_X",
      nameZn: "水龟河道材质选择",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "TimeCollCycle",
      nameZn: "定时报采集周期",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "I4_Data",
      nameZn: "4mA对应采集值",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "I20_Data",
      nameZn: "20mA对应采集值",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "Camera_Hours",
      nameZn: "摄像头整点采集设置",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "ServerOtherConfig",
      nameZn: "BIT0-BIT4补发数据选项",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "OtherConfig",
      nameZn: "保留其它配置相关",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "LongitudeCompe",
      nameZn: "经度补偿",
      type: "int",
      num: 4,
      value: "",
     analysis: false,
    },
    {
      name: "LatitudinalCompe",
      nameZn: "纬度补偿",
      type: "int",
      num: 4,
      value: "",
     analysis: false,
    },
    {
      name: "EDHight",
      nameZn: "蒸发皿传感器安装高度单位",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "EDRange",
      nameZn: "蒸发皿传感器量程",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "EDMinAddWater",
      nameZn: "蒸发皿最小加水量",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "SSMHight",
      nameZn: "土壤沉降传感器安装高度单位",
      type: "u",
      num: 256,
      value: "",
     analysis: false,
    },
    {
      name: "SSMRange",
      nameZn: "土壤沉降传感器量程",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "SSMRange",
      nameZn: "土壤沉降传感器量程",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "SlaveParameter",
      nameZn: "从机参数",
      type: "u",
      num: 144,
      value: "",
     analysis: false,
    },
    {
      name: "WQCorrParame",
      nameZn: "水质修正系数",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },

    {
      name: "WLA",
      nameZn: "补盲距离",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "EXTDTU_UpFREQ",
      nameZn: "上行频率",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "EXTDTU_DownFREQ",
      nameZn: "下行频率",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "StartYear",
      nameZn: "数据起始年",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "Startmonth",
      nameZn: "数据起始月",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "StartDate",
      nameZn: "数据起始日",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "RS485_CH1_WarmTime",
      nameZn: "RS485 通道1预热时间",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "RS485_CH3_WarmTime",
      nameZn: "RS485 通道3预热时间",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "RS485_CH2_WarmTime",
      nameZn: "RS485 通道2预热时间",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "REV_WARM_TIME",
      nameZn: "预留几个预热时间设置",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterQuality_Cycle",
      nameZn: "常规水质传感器采集周期",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "Meather_Cycle",
      nameZn: "常规气象传感器采集周期",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "Camera_Cycle",
      nameZn: "工业相机采集周期",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WQCorrParame",
      nameZn: "",
      type: "u",
      num: 80,
      value: "",
     analysis: false,
    },
    {
      name: "ManualSet",
      nameZn: "人工置数",
      type: "s",
      num: 80,
      value: "",
     analysis: false,
    },
    {
      name: "InsideDTU_Lora_KEY",
      nameZn: "内置DTUlora加密key",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "InsideDTU_Lora_ADD",
      nameZn: "内置DTUlora地址",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "ServerPassward",
      nameZn: "服务器密码",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "I4_20_Offset",
      nameZn: "内置4-20mA采集偏移",
      type: "s",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "I4_20_Parame",
      nameZn: "内置4-20mA采集线性修正值",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "InsFlowHeight",
      nameZn: "流速仪安装高度",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "InsFlowCV",
      nameZn: "流量校正系数",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "FlowSlotSedim",
      nameZn: "流速槽淤积深度",
      type: "u",
      num: 96,
      value: "",
     analysis: false,
    },
    {
      name: "FlowSlotParameter",
      nameZn: "流速槽参数",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "FilterTimes_J",
      nameZn: "流速，水位，SS滤波次数",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "FlowPipDir",
      nameZn: "管道方向 bit0:流量计1管道方向",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "FlowDirection",
      nameZn: "流量计安装方向",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "TURBHeight",
      nameZn: "浊度计安装高度",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "FilterRange",
      nameZn: "流速，水位，SS滤波波动阈值",
      type: "u",
      num: 28,
      value: "",
     analysis: false,
    },
    {
      name: "FilterTimes_S",
      nameZn: "流速，水位，SS滤波次数",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "rev8",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "FilterThreshold",
      nameZn: "流速，水位，SS滤波门限",
      type: "u",
      num: 48,
      value: "",
     analysis: false,
    },
    {
      name: "FlowDrect_WLValve",
      nameZn: "",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "FlowDrect_FLValve[",
      nameZn: "",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "FlowDrect_HoldCnt",
      nameZn: "",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "Reserve16",
      nameZn: "保留",
      type: "u",
      num: 48,
      value: "",
     analysis: false,
    },
    {
      name: "ServiceID",
      nameZn: "",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterQuality_Enable",
      nameZn: "常规水质传感器开关",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "WLRevise",
      nameZn: "水位修正值 ",
      type: "s",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "Meather_Enable",
      nameZn: "常规气象传感器开关",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevel_Addr",
      nameZn: "水位计地址",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "SSM_Addr",
      nameZn: "土壤沉降仪地址",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "ED_Addr",
      nameZn: "蒸发皿传感器地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },

    {
      name: "NH4N_Addr",
      nameZn: "氨氮地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "HNO3_Addr",
      nameZn: "硝酸盐地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CHLA_Addr",
      nameZn: "叶绿素a地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "ALGAE_Addr",
      nameZn: "蓝绿藻地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "REDOX_Addr",
      nameZn: "氧化还原电位",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: " COD_Addr",
      nameZn: "COD通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "res9",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Pressure_Addr",
      nameZn: "气压传感器地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Wind_Add",
      nameZn: "风速风向传感器地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "AirTempHump_Addr",
      nameZn: "空气温湿度传感器地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "DO_Addr",
      nameZn: "DO",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "GateLevel_Addr",
      nameZn: "闸位计地址",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "COND_Addr",
      nameZn: "COND",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Radiation_Addr",
      nameZn: "辐射传感器",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PM25_Addr",
      nameZn: "PM2.5通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "SoilMois_Addr",
      nameZn: "墒情传感器地址",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "WaterFlow_Addr",
      nameZn: "流量计地址",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "Tra_Addr",
      nameZn: "透明度地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PH_Add",
      nameZn: "PH通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WaterTemp_Addr",
      nameZn: "水温通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Camera_Addr",
      nameZn: "摄像头地址",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "res8",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "BOD_Add",
      nameZn: "BOD地址",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "OIW_Addr",
      nameZn: "水中油",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CL_Addr",
      nameZn: "余氯地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WQCorrParameSelect",
      nameZn: "水质类型修正参数选择",
      type: "u",
      num: 40,
      value: "",
     analysis: false,
    },
    {
      name: " RS485_CH1_Retry",
      nameZn: "RS485通道1采集数据无效重试次数",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "RS485_CH3_Retry",
      nameZn: "RS485通道3采集数据无效重试次数",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "RS485_CH2_Retry",
      nameZn: "其他传感器数据无效重试次数",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevel_Enable",
      nameZn: "水位计开关状态",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "oilMois_Enable",
      nameZn: "墒情开关状态",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WaterFlow_Enable;",
      nameZn: "流量开关状态",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: " res8_5",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Camera_Enable",
      nameZn: "工业相机开关",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CumlFlow_Enable;",
      nameZn: "累计流量开关",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "GateLevel_Enable;",
      nameZn: "闸位计开关",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "SendFlag",
      nameZn: "发送标志BIT0 0汛期需要时间加报",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "SSM_Enable",
      nameZn: "土壤沉降仪开关",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TURB_Add",
      nameZn: "悬浮物通信地址",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "SQ_Addr",
      nameZn: "泥沙通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TN_Addr",
      nameZn: "总氮通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TP_Addr",
      nameZn: "总磷通信地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "REV_ENABLE",
      nameZn: "预留几个开关设置",
      type: "u",
      num: 72,
      value: "",
     analysis: false,
    },
    {
      name: "RainAlarm",
      nameZn: "雨量加报阈值",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "RainTimeReport_Enable",
      nameZn: "时段雨量使能",
      type: "bool",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "RainRes",
      nameZn: "雨量计分辨率",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CentralAddr",
      nameZn: "中心站地址编码",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "VoltageAlarm",
      nameZn: "电池低电压报警",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "VoltageProte",
      nameZn: "电池低电压保护,将缩短发送周期,保护电池",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },


    {
      name: "ConfigStr0",
      nameZn: "可配置字符串，mqtt用于token或者用户名（定制），212用于站码",
      type: "char",
      num: 22,
      value: "",
     analysis: true,
    },
    {
      name: "ConfigStr1",
      nameZn: "可配置字符串，mqtt用于密码",
      type: "char",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "ManualSetSelect",
      nameZn: "人工置数参数选择",
      type: "u",
      num: 40,
      value: "",
     analysis: false,
    },
    {
      name: " res8_4",
      nameZn: "",
      type: "u",
      num: 48,
      value: "",
     analysis: false,
    },
    {
      name: "HeartbeatTime",
      nameZn: "心跳包,链路维持报",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "es8_6",
      nameZn: "",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: " Camera_TimeSlot",
      nameZn: "相机发送时间段",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "res8_2",
      nameZn: "",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevelChangeAlarm",
      nameZn: "水位变化加报 河道1min监测加报",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "res899",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WorkingMode",
      nameZn: "工作模式设置,用于设置是否常在线模式",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "DoorAlarmTime",
      nameZn: "柜门报警等待延时",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: " res8_10",
      nameZn: "",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: " res8_9",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "EnableTiming",
      nameZn: "是否自动校时",
      type: "bool",
      num: 1,
      value: "",
     analysis: false,
    },
    {
      name: " Camera_PicAck",
      nameZn: "图片报文响应设置",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PicPackSendDelay",
      nameZn: "图片报文包发送延时",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: " res8_0",
      nameZn: "",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "VpnPoint",
      nameZn: "VPN接入点",
      type: "char",
      num: 34,
      value: "",
     analysis: false,
    },
    {
      name: "VpnName",
      nameZn: "VPN用户名",
      type: "u",
      num: 34,
      value: "",
     analysis: false,
    },
    {
      name: "VpnPassword",
      nameZn: "VPN密码",
      type: "u",
      num: 34,
      value: "",
     analysis: false,
    },
    {
      name: "VpnEnable",
      nameZn: "VPN使能，服务器1-3",
      type: "bool",
      num: 1,
      value: "",
     analysis: false,
    },
    {
      name: "RemoteVpnEnable",
      nameZn: "远程服务器是否是能VPN，也就是后台服务器是否是能VPN，一般情况下为0",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "BODSelect",
      nameZn: "BOD型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "DomainEnable",
      nameZn: "bit0-bin3:中心站1-3,域名使能",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Domain",
      nameZn: "服务器域名",
      type: "char",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "DitchType",
      nameZn: "流量计截面选择",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "FlowUnit",
      nameZn: "流量传输方式，0：流量m3/s；1：水量m3/h",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "FlowChanRes",
      nameZn: "非标准堰高度分辨率，总共256个点，1-100cm可设置",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevelSensor",
      nameZn: "水位数据来源",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterTempSensor",
      nameZn: "水温数据来源",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "FaultFilter",
      nameZn: "传感器故障滤波次数",
      type: "u",
      num: 24,
      value: "",
     analysis: true,
    },
    {
      name: "OIWSelect",
      nameZn: "水中油型号",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CLSelect",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "es8_3",
      nameZn: "",
      type: "u",
      num: 40,
      value: "",
     analysis: false,
    },
    {
      name: "WaterLevelDeviceSelect",
      nameZn: "水位计设备选择",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "WaterFlowDeviceSelect",
      nameZn: "流量计设备选择",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "CamerDeviceSelect",
      nameZn: "相机型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "DODeviceSelect",
      nameZn: "DO设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CODDeviceSelect",
      nameZn: "COD设备型号选择-预留",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CONDDeviceSelect",
      nameZn: "COND设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PHDeviceSelect",
      nameZn: "PH设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TempHumSelect",
      nameZn: "温湿度设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WaterTempSelect",
      nameZn: "水温设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "GateLevelDeviceSelect",
      nameZn: "闸位计选择-8个闸位计只能使用一种类型的",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PressureSelect",
      nameZn: "气压传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WindSelect",
      nameZn: "风速风向传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "RadiationSelect",
      nameZn: "辐射传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "res8_7",
      nameZn: "",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: "SoilMoistureSelect",
      nameZn: "土壤墒情传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "REDOXSelect",
      nameZn: "氧化还原电位传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "NH4NSelect",
      nameZn: "氨氮传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "HNO3Select",
      nameZn: "硝酸盐传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "CHLASelect",
      nameZn: "叶绿素a传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "ALGAESelect",
      nameZn: "蓝绿藻传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "ServerPassward",
      nameZn: "增加蒸发皿配置",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "EDSelect",
      nameZn: "蒸发皿传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "SSMSelect",
      nameZn: "土壤沉降传感器选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TURBDeviceSelect",
      nameZn: "SS设备型号选择",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "SQDeviceSelect",
      nameZn: "泥沙设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "PM25DeviceSelect",
      nameZn: "PM2.5设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TNSelect",
      nameZn: "总氮设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TPSelect",
      nameZn: "总磷设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TraSelect",
      nameZn: "透明度设备型号选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "Reserve8_2",
      nameZn: "传感器选择预留",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "InstFlowAccuSelect",
      nameZn: "瞬时流量精度选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "ExtAlarmTime",
      nameZn: "外置通信模块通信",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },


    {
      name: "DataSave_Cycel",
      nameZn: "数据存储周期",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "WaterFlowLevelSelect",
      nameZn: "流量计水位数据来源",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "EXTDTU_Select",
      nameZn: "外置DTU厂家选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "NBIOT_Enable",
      nameZn: "NBIOT开关，低4位为中心站1-3，高4位为后台设置(主卡)，设置为0xA为开启，否则为关闭",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "NBIOT_Mode",
      nameZn: "NBIOT模式选择",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "EDWaterLevelSelect",
      nameZn: "蒸发皿水位来源",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "TURBTestWaterLevelSelect",
      nameZn: "SS的水位来源选择",
      type: "u",
      num: 16,
      value: "",
     analysis: false,
    },
    {
      name: "SlaveAddr",
      nameZn: "从机模式地址",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "SlaveEnable",
      nameZn: "从机模式开关",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "SlaveDeviceSelect",
      nameZn: "从机驱动选择",
      type: "u",
      num: 24,
      value: "",
     analysis: false,
    },
    {
      name: "SoilTempSelect",
      nameZn: "土壤温度数据来源",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "GTPSelect",
      nameZn: "地温数据来源",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "EXTDTU_LoRa_JOINEUI",
      nameZn: "设置JoinEUI",
      type: "u",
      num: 64,
      value: "",
     analysis: false,
    },
    {
      name: " InsideDTU_Lora_NID",
      nameZn: "内置DTUlora网络id",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: " WGX5_Gain",
      nameZn: "小雷达增益",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "WGX6_NP",
      nameZn: "大雷达忽略的距离",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "WGX6_PO",
      nameZn: "大雷达发射功率0",
      type: "u",
      num: 16,
      value: "",
     analysis: true,
    },
    {
      name: "InsideDTU_Lora_NUM",
      nameZn: "网关模组数量，用于判断网关地址",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "ThresholdCollCycle",
      nameZn: "阈值采集周期需要和定时报采集周期比较选小的",
      type: "u",
      num: 24,
      value: "",
     analysis: true,
    },
    {
      name: "ThresholdAlarmCycle",
      nameZn: "阈值加报周期",
      type: "u",
      num: 24,
      value: "",
     analysis: true,
    },
    {
      name: "AlarmCollCycle",
      nameZn: "定时报采集周期汛期",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "AlarmCycle",
      nameZn: "加报发送周期",
      type: "u",
      num: 8,
      value: "",
     analysis: true,
    },
    {
      name: "es8_1",
      nameZn: "",
      type: "u",
      num: 8,
      value: "",
     analysis: false,
    },
    {
      name: "WLBase",
      nameZn: "井盖高程 ",
      type: "s",
      num: 64,
      value: "",
     analysis: true,
    },
    {
      name: "Reserve8_3",
      nameZn: "",
      type: "u",
      num: 32,
      value: "",
     analysis: false,
    },
  ]
})

